
// AUTOGENERATED — exports_ops_generated.cpp
#include <cstdint>
extern "C" int __stdcall AlglibBridge_Process(
  unsigned int operation,
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms);


extern "C" __declspec(dllexport) int __stdcall AlglibOp_PING(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(0, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_FILTER_GAUSSIAN(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(13, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_DENOISE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(16, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_UPSCALE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(17, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_ANALYZE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(21, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_PHASE_UNWRAP(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(24, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}

