
// AUTOGENERATED — exports_ops_generated.cpp
#include <cstdint>
extern "C" int __stdcall AlglibBridge_Process(
  unsigned int operation,
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms);


extern "C" __declspec(dllexport) int __stdcall AlglibOp_PING(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(0, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_FFT_COMPLEX_FORWARD(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(1, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_FFT_COMPLEX_INVERSE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(2, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_FFT_REAL_FORWARD(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(3, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_FFT_REAL_INVERSE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(4, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_FFT_SINE_TRANSFORM(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(5, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_FFT_COSINE_TRANSFORM(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(6, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_FFT_TWO_REAL(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(7, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_RESAMPLE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(10, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_ZERO_PAD(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(11, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_REMOVE_DC(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(12, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_FILTER_GAUSSIAN(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(13, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_FILTER_NOTCH(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(14, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_APPLY_MASK(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(15, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_DENOISE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(16, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_UPSCALE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(17, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_DOWNSCALE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(18, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_CONVOLUTION(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(19, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_CORRELATION(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(20, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_ANALYZE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(21, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_DETECT_TRANSITIONS(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(22, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_INSTANT_METRICS(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(23, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SPECTRAL_PHASE_UNWRAP(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(24, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SSA_CREATE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(200, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SSA_DESTROY(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(201, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SSA_CONFIGURE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(202, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SSA_CLEAR(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(203, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SSA_ADD_SEQUENCE(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(204, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SSA_APPEND_POINT(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(205, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SSA_ANALYZE_LAST(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(206, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}


extern "C" __declspec(dllexport) int __stdcall AlglibOp_SSA_FORECAST_LAST(
  const double* primary, int primary_len,
  const double* secondary, int secondary_len,
  const unsigned char* params, int param_len,
  double* out_primary, int out_primary_cap, int* out_primary_len,
  double* out_secondary, int out_secondary_cap, int* out_secondary_len,
  unsigned char* out_extra, int out_extra_cap, int* out_extra_len,
  int timeout_ms)
{
  return AlglibBridge_Process(207, primary, primary_len, secondary, secondary_len,
    params, param_len, out_primary, out_primary_cap, out_primary_len,
    out_secondary, out_secondary_cap, out_secondary_len,
    out_extra, out_extra_cap, out_extra_len, timeout_ms);
}

